export enum actionTypes {
    DELETE_ITEM = "DELETE_ITEM",
    SET_FILTER = "SET_FILTER",
    DELETE_COMPLETED = "DELETE_COMPLETED",
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE ",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST',
    FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE',
    ADD_TASK_REQUEST = 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE = 'ADD_TASK_FAILURE',
    EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST',
    EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE'
}
